#!/usr/bin/env python3
"""
GENERATED BY CODEX, ADJUSTED BY HUMAN
Summarize per-thread runtimes plus generation/GPU/memory averages from CSV files.

For every CSV file in the specified directory the script:
  • finds any entries with both a thread count (num_threads by default) and a runtime
    and averages them by thread count,
  • computes mean values for generation_times, average_gpu_memory_usage, and average_gpu_utilization,
  • writes one CSV row per input file, with columns named runtime_<threads> plus
    avg_generation_time, avg_gpu_memory_usage, avg_gpu_utilization.

Missing metrics remain NaN in the CSV.
"""
import os
import argparse
from pathlib import Path
from statistics import mean
from typing import Any, Dict, List, Set

import numpy as np

import pandas as pd
# --------------------------------------------------------------------------- #
# argument parsing                                                            #
# --------------------------------------------------------------------------- #
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "input_dir",
        type=str,
        help="Directory containing CSV result files.",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        default="csv_runtime_summary.csv",
        help="Name (or path) of the CSV to write (default: csv_runtime_summary.csv).",
    )
    parser.add_argument(
        "--runtime-key",
        type=str,
        default="runtime",
        help="Column name for runtime values (default: runtime).",
    )
    parser.add_argument(
        "--threads-key",
        type=str,
        default="num_threads",
        help="Column name that stores the thread count (default: num_threads).",
    )
    return parser.parse_args()


# --------------------------------------------------------------------------- #
# per-file processing                                                         #
# --------------------------------------------------------------------------- #
def summarize_file(
    csv_path: Path,
    runtime_key: str,
    threads_key: str,
) -> Dict[str, Any]:
    """
    Read a CSV file and compute:
      - Average runtime per thread count
      - Average generation_times
      - Average average_gpu_memory_usage
      - Average average_gpu_utilization
      - Average vram utilizatoin
    """
    df = pd.read_csv(csv_path)
    
    row: Dict[str, Any] = {"model": csv_path.stem}

    # Per-thread runtime averages
    if runtime_key in df.columns and threads_key in df.columns:
        # Filter out rows where runtime or threads are NaN
        valid_rows = df[[runtime_key, threads_key]].dropna()
        
        if not valid_rows.empty:
            per_threads: Dict[float, List[float]] = {}
            for _, r in valid_rows.iterrows():
                threads = float(r[threads_key])
                runtime = float(r[runtime_key])
                per_threads.setdefault(threads, []).append(runtime)
            
            for threads, runtimes in per_threads.items():
                # Convert to int if it's a whole number
                thread_label = int(threads) if threads == int(threads) else threads
                row[f"runtime_{thread_label}"] = mean(runtimes)

    # Average generation times
    if "generation_times" in df.columns:
        gen_times = pd.to_numeric(df["generation_times"], errors='coerce').dropna()
        row["avg_generation_time"] = float(gen_times.mean()) if not gen_times.empty else np.nan
    else:
        row["avg_generation_time"] = np.nan

    # Average GPU memory usage
    if "average_gpu_memory_usage" in df.columns:
        gpu_mem = pd.to_numeric(df["average_gpu_memory_usage"], errors='coerce').dropna()
        row["avg_gpu_memory_usage"] = float(gpu_mem.mean()) if not gpu_mem.empty else np.nan
    else:
        row["avg_gpu_memory_usage"] = np.nan

    # Average GPU utilization
    if "average_gpu_utilization" in df.columns:
        gpu_util = pd.to_numeric(df["average_gpu_utilization"], errors='coerce').dropna()
        row["avg_gpu_utilization"] = float(gpu_util.mean()) if not gpu_util.empty else np.nan
    else:
        row["avg_gpu_utilization"] = np.nan
    # Average vram 
    if "virtual_memory_used" in df.columns:
  
        gpu_util = pd.to_numeric(df["virtual_memory_used"], errors="coerce").dropna()
        row["avg_virtual_memory_used"] = float(gpu_util.mean()) if not gpu_util.empty else np.nan
    else:
        row["avg_virtual_memory_used"] = np.nan
    #print(row["avg_virtual_memory_used"])
    return row


def main() -> None:
    args = parse_args()

    input_dir = Path(args.input_dir).resolve()
    if not input_dir.is_dir():
        raise SystemExit(f"Error: {input_dir} is not a directory.")

    # ---- Only look for these 5 files ----
    required_files = [
        "hpc-coder_combined.csv",
        "magicoder_combined.csv",
        "sonnet_combined.csv",
        "starcoder_combined.csv",
        "gpt5_combined.csv",
        "minimax_combined.csv", 
        "glm_combined.csv", 
        "oss_combined.csv"
    ]
    
    csv_files: List[Path] = []
    for fname in required_files:
        fpath = input_dir / fname
        if not fpath.is_file():
            if fname == "gpt5_combined.csv":
                new_fpath = input_dir / "gpt-5_combined.csv"
                if not new_fpath.is_file():
                    print(f"Warning: Missing file {fname} (tried {fpath} and {new_fpath})")
                    continue
                else: 
                    fpath = new_fpath 
            else:
                print(f"Warning: Missing file {fname}")
                continue
        csv_files.append(fpath)

    if not csv_files:
        raise SystemExit("No valid CSV files found.")

    rows: List[Dict[str, Any]] = []
    thread_counts: Set[float] = set()

    for csv_path in csv_files:
        try:
            row = summarize_file(csv_path, args.runtime_key, args.threads_key)
            
        except Exception as exc:
            print(f"Warning: skipping {csv_path} ({exc})")
            continue

        rows.append(row)
        for key in row:
            if key.startswith("runtime_"):
                try:
                    thread_val = key.split("_", 1)[1]
                    thread_counts.add(float(thread_val))
                except ValueError:
                    pass

    if not rows:
        raise SystemExit("No valid entries were found in the CSV files.")

    # Sort thread counts (convert to int if whole numbers)
    sorted_threads = sorted(thread_counts)
    runtime_cols = []
    for t in sorted_threads:
        if t == int(t):
            runtime_cols.append(f"runtime_{int(t)}")
        else:
            runtime_cols.append(f"runtime_{t}")
    
    columns = (
        ["model"]
        + runtime_cols
        + ["avg_generation_time", "avg_gpu_memory_usage", "avg_gpu_utilization", "avg_virtual_memory_used"]
    )

    df = pd.DataFrame(rows)
    df = df.reindex(columns=columns)

    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = input_dir / output_path
    df.to_csv(output_path, index=False)
    print(f"Wrote runtime summary to {output_path}")


if __name__ == "__main__":
    main()
