// #include <hpx/include/parallel_algorithm.hpp>
// #include <hpx/include/parallel_execution.hpp>
#include <hpx/hpx_init.hpp>
#include <hpx/include/iostreams.hpp>
// #include <hpx/include/parallel_for_loop.hpp>
// #include <hpx/include/lcos.hpp>
// #include <hpx/include/parallel_for_each.hpp>
// #include <hpx/include/parallel_generate.hpp>
// #include <hpx/include/parallel_transform_reduce.hpp>
// #include <hpx/execution.hpp>
//HPX 1.5.1
#include <hpx/algorithm.hpp>
#include <hpx/any.hpp>
#include <hpx/barrier.hpp>
#include <hpx/channel.hpp>
#include <hpx/chrono.hpp>
#include <hpx/distributed/runtime.hpp>
#include <hpx/execution.hpp>
#include <hpx/functional.hpp>
#include <hpx/future.hpp>
#include <hpx/hpx.hpp>
#include <hpx/include/actions.hpp>
#include <hpx/include/agas.hpp>
#include <hpx/include/applier.hpp>
#include <hpx/include/apply.hpp>
#include <hpx/include/async.hpp>
#include <hpx/include/bind.hpp>
#include <hpx/include/client.hpp>
#include <hpx/include/components.hpp>
#include <hpx/include/compute.hpp>
#include <hpx/include/dataflow.hpp>
#include <hpx/include/datapar.hpp>
#include <hpx/include/future.hpp>
#include <hpx/include/lcos.hpp>
#include <hpx/include/lcos_local.hpp>
#include <hpx/include/naming.hpp>
#include <hpx/include/parallel_adjacent_difference.hpp>
#include <hpx/include/parallel_adjacent_find.hpp>
#include <hpx/include/parallel_algorithm.hpp>
#include <hpx/include/parallel_all_any_none_of.hpp>
#include <hpx/include/parallel_container_algorithm.hpp>
#include <hpx/include/parallel_copy.hpp>
#include <hpx/include/parallel_count.hpp>
#include <hpx/include/parallel_destroy.hpp>
#include <hpx/include/parallel_equal.hpp>
#include <hpx/include/parallel_exception_list.hpp>
#include <hpx/include/parallel_execution.hpp>
#include <hpx/include/parallel_execution_policy.hpp>
#include <hpx/include/parallel_executor_information.hpp>
#include <hpx/include/parallel_executor_parameters.hpp>
#include <hpx/include/parallel_executors.hpp>
#include <hpx/include/parallel_fill.hpp>
#include <hpx/include/parallel_find.hpp>
#include <hpx/include/parallel_for_each.hpp>
#include <hpx/include/parallel_for_loop.hpp>
#include <hpx/include/parallel_generate.hpp>
#include <hpx/include/parallel_is_heap.hpp>
#include <hpx/include/parallel_is_partitioned.hpp>
#include <hpx/include/parallel_is_sorted.hpp>
#include <hpx/include/parallel_lexicographical_compare.hpp>
#include <hpx/include/parallel_memory.hpp>
#include <hpx/include/parallel_merge.hpp>
#include <hpx/include/parallel_minmax.hpp>
#include <hpx/include/parallel_mismatch.hpp>
#include <hpx/include/parallel_move.hpp>
#include <hpx/include/parallel_numeric.hpp>
#include <hpx/include/parallel_partition.hpp>
#include <hpx/include/parallel_reduce.hpp>
#include <hpx/include/parallel_remove.hpp>
#include <hpx/include/parallel_remove_copy.hpp>
#include <hpx/include/parallel_replace.hpp>
#include <hpx/include/parallel_reverse.hpp>
#include <hpx/include/parallel_rotate.hpp>
#include <hpx/include/parallel_scan.hpp>
#include <hpx/include/parallel_search.hpp>
#include <hpx/include/parallel_set_operations.hpp>
#include <hpx/include/parallel_sort.hpp>
#include <hpx/include/parallel_swap_ranges.hpp>
#include <hpx/include/parallel_task_block.hpp>
#include <hpx/include/parallel_transform.hpp>
#include <hpx/include/parallel_transform_reduce.hpp>
#include <hpx/include/parallel_transform_scan.hpp>
#include <hpx/include/parallel_uninitialized_copy.hpp>
#include <hpx/include/parallel_uninitialized_default_construct.hpp>
#include <hpx/include/parallel_uninitialized_fill.hpp>
#include <hpx/include/parallel_uninitialized_move.hpp>
#include <hpx/include/parallel_uninitialized_value_construct.hpp>
#include <hpx/include/parallel_unique.hpp>
#include <hpx/include/parcel_coalescing.hpp>
#include <hpx/include/parcelset.hpp>
#include <hpx/include/performance_counters.hpp>
#include <hpx/include/plain_actions.hpp>
#include <hpx/include/resource_partitioner.hpp>
#include <hpx/include/run_as.hpp>
#include <hpx/include/runtime.hpp>
#include <hpx/include/serialization.hpp>
#include <hpx/include/sync.hpp>
#include <hpx/include/thread_executors.hpp>
#include <hpx/include/threadmanager.hpp>
#include <hpx/include/threads.hpp>
#include <hpx/include/traits.hpp>
#include <hpx/include/util.hpp>
#include <hpx/latch.hpp>
#include <hpx/local/execution.hpp>
#include <hpx/local/future.hpp>
#include <hpx/local/runtime.hpp>
#include <hpx/memory.hpp>
#include <hpx/numeric.hpp>
#include <hpx/optional.hpp>
#include <hpx/runtime.hpp>
#include <hpx/task_block.hpp>
#include <hpx/tuple.hpp>
#include <hpx/type_traits.hpp>
#include <hpx/iterator_support/counting_iterator.hpp>
#include <hpx/iterator_support/iterator_adaptor.hpp>
#include <hpx/iterator_support/iterator_facade.hpp>
#include <hpx/iterator_support/iterator_range.hpp>
#include <hpx/iterator_support/range.hpp> 
#include <hpx/iterator_support/traits/is_iterator.hpp>
#include <hpx/iterator_support/traits/is_range.hpp>
#include <hpx/iterator_support/traits/is_sentinel_for.hpp>
#include <hpx/iterator_support/transform_iterator.hpp> 
//actions
#include <hpx/actions/action_support.hpp>
#include <hpx/actions/actions_fwd.hpp>
#include <hpx/actions/base_action.hpp>
#include <hpx/actions/register_action.hpp>
#include <hpx/actions/transfer_action.hpp>
#include <hpx/actions/transfer_base_action.hpp>
#include <hpx/actions/transfer_continuation_action.hpp>
#include <hpx/algorithms/traits/is_value_proxy.hpp>
#include <hpx/algorithms/traits/projected.hpp>
#include <hpx/algorithms/traits/projected_range.hpp>
//parallel algorithm
#include <hpx/actions/action_support.hpp>
#include <hpx/actions/actions_fwd.hpp>
#include <hpx/actions/base_action.hpp>
#include <hpx/actions/register_action.hpp>
#include <hpx/actions/transfer_action.hpp>
#include <hpx/actions/transfer_base_action.hpp>
#include <hpx/actions/transfer_continuation_action.hpp>
#include <hpx/algorithms/traits/is_value_proxy.hpp>
#include <hpx/algorithms/traits/projected.hpp>
#include <hpx/algorithms/traits/projected_range.hpp>
#include <hpx/parallel/algorithm.hpp>
#include <hpx/parallel/algorithms/adjacent_difference.hpp>
#include <hpx/parallel/algorithms/adjacent_find.hpp>
#include <hpx/parallel/algorithms/all_any_none.hpp>
#include <hpx/parallel/algorithms/copy.hpp>
#include <hpx/parallel/algorithms/count.hpp>
#include <hpx/parallel/algorithms/destroy.hpp>
#include <hpx/parallel/algorithms/equal.hpp>
#include <hpx/parallel/algorithms/for_loop.hpp>
#include <hpx/parallel/algorithms/for_each.hpp>


//GENERAL INCLUDES
#include <algorithm>
#include <bitset>
#include <complex>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <istream>
#include <iterator>
#include <limits>
#include <list>
#include <locale>
#include <map>
#include <memory>
#include <new>
#include <numeric>
#include <ostream>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <streambuf>
#include <string>
#include <typeinfo>
#include <utility>
#include <valarray>
#include <vector>
// C++11 additions
#include <array>
#include <atomic>
#include <chrono>
#include <codecvt>
#include <condition_variable>
#include <forward_list>
#include <future>
#include <initializer_list>
#include <mutex>
#include <random>
#include <ratio>
#include <regex>
#include <scoped_allocator>
#include <system_error>
#include <thread>
#include <tuple>
#include <type_traits>
#include <typeindex>
#include <unordered_map>
#include <unordered_set>
//c library facilities
#include <cassert>
#include <clocale>
#include <cstdarg>
#include <cstring>
#include <cctype>
#include <cmath>
#include <cstddef>
#include <ctime>
#include <cerrno>
#include <csetjmp>
#include <cstdio>
#include <cwchar>
#include <cfloat>
#include <csignal>
#include <cstdlib>
#include <cwctype>
#include <climits>
#include <cfenv>
#include <cinttypes>
#include <cstdint>
#include <cuchar>
#include <optional>