#!/usr/bin/env python3
"""
merge_includes.py

Extract the union of #include directives from two header files
and write the unique, sorted includes into a new header file.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Set


INCLUDE_RE = re.compile(r'^\s*#\s*include\s+[<"].+[>"]')


def extract_includes(path: Path) -> Set[str]:
    """Return the set of #include lines (verbatim) found in the file."""
    includes: Set[str] = set()
    with path.open("r", encoding="utf-8") as infile:
        for line in infile:
            if INCLUDE_RE.match(line):
                includes.add(line.strip())
    return includes


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Merge includes from two header files into a new header."
    )
    parser.add_argument("header1", type=Path, help="First header file.")
    parser.add_argument("header2", type=Path, help="Second header file.")
    parser.add_argument(
        "output",
        nargs="?",
        default="combined.hpp",
        help="Output header file (default: combined.hpp).",
    )
    args = parser.parse_args()

    for path in (args.header1, args.header2):
        if not path.exists():
            parser.error(f"File not found: {path}")

    includes1 = extract_includes(args.header1)
    includes2 = extract_includes(args.header2)

    combined = sorted(includes1 | includes2)

    output_path = Path(args.output)
    with output_path.open("w", encoding="utf-8") as outfile:
        outfile.write("// Automatically generated by merge_includes.py\n")
        outfile.write("// Combined includes from:\n")
        outfile.write(f"//   {args.header1}\n")
        outfile.write(f"//   {args.header2}\n\n")
        for include in combined:
            outfile.write(f"{include}\n")

    print(f"Wrote {len(combined)} unique includes to {output_path}")


if __name__ == "__main__":
    main()
