#!/usr/bin/env python3
"""
Parse and categorize compilation and runtime errors from HPX validation results.

Directory-based usage:
    python error_extraction.py <input_directory> <output_directory>

Example:
    python error_extraction.py \
        /work/pi_mrobson_smith_edu/scratch/generation_hpx/la/driver/tcmalloc \
        /work/pi_mrobson_smith_edu/scratch/generation_hpx/la/driver/tcmalloc/errors

Input directory is expected to contain files with names aong the lines of [model_name]_combined.json

Currently, for HPX only the following models are analyzed because they contain
recorded stderr:
    glm
    minimax
    oss

Output:
    <output_directory>/glm_errors.csv
    <output_directory>/minimax_errors.csv
    <output_directory>/oss_errors.csv

]

Important runtime behavior: 
    Build: Only look at did_build is false, as we ignore any validation fails. This is only compile errors and issues at runtime
    Run: Look only at did_run False, but ignore if issue is timeout. By default, this ignores validation fail (not a real runtime error)
    For each generated output, only the FIRST run containing nonempty stderr
    is analyzed. This prevents the same runtime error from being counted once
    TIMEOUT DOES NOT COUNT as a runtime error. It can be treated the same way as how we ignore validation fail - it runs and probably will wrap up, the issue is that hte code doesn't work by guidelines. Caveat is if the futures useage is incorrect in that there is no promise or retrieval mechanism, we can't log such an error 
    for every thread count (1, 2, 4, 8, 16, 32, 64). The thread count of the FIRST error is also recorded
    Actualy, we're only looking at thread cts 1 and 2


Base code generated by AI, adjusted by human.
"""

import csv
import json
import os
import re
import sys
from collections import defaultdict
from typing import Any, Dict, List, Optional


# ============================================================================
# MODELS TO ANALYZE
# ============================================================================

# Only these models currently have stderr recorded.
SUPPORTED_MODELS = {
    "gpt5",
    "gpt-5",
    "sonnet", 
    "hpc-coder",
    "magicoder",
    "oss",
    #one day, GEMMA 
}

# VALIDATION FAIL BUT DID_RUN RECORDED AS FALSE TOO (BECAUSE THE OUTPUT ITSELF JUST CAN'T BE USED FOR COMPARISON IN UTILITIES_OLD)
# THIS IS FILTERED OUT SINCE WE DON'T CARE ABOUT VALIDATION FAIL
#also exclude timeout patterns , 
IGNORE_PATTERNS_RUNTIME = [
    r"utilities_old\.hpp:.*fequal.*Assertion.*a\.size\(\)\s*==\s*b\.size\(\).*failed",
    r"\[Timeout\]"
]
# see if it has above patterns
def ignore_runtime_stderr(stderr: str) -> bool:
    if not stderr:
        return True

    return any(
        re.search(pattern, stderr, re.IGNORECASE)
        for pattern in IGNORE_PATTERNS_RUNTIME
    )

    
# ============================================================================
# ERROR CATEGORIES AND PATTERNS
# ============================================================================

ERROR_CATEGORIES = {
    # Boost-specific errors (NOT RELEVANT HERE)
    "Boost_Error": {
        "patterns": [
            r"is not a member of .*boost::",
            r"boost::.*is not a member",
            r"error.*boost::serialization",
            r"error.*boost::numeric",
            r"Boost.Config",
        ],
        "description": "Boost version incompatibility (not LLM fault)",
    },
    
    
    "Syntax_Error": {
        "patterns": [
            # Combinations of malformed source and HPX/API misuse
            r"stray .* in program",
            r"digit separator outside digit sequence",
            r"character constant too long for its type",
            r"invalid preprocessing directive",
            r"missing terminating .* character",
            r"extended character",
            r"else.*without a previous.*if",
            r"continue statement not within a loop",
            r"unterminated",
            r"expected .* at end of input",
            r"expected .* at end of",
            r"empty character constant",
            r"too many decimal points in number",
            r"expected primary-expression",
            r"expected.*before.*token",
            r"missing terminating ['\"] character",
            r"is not captured",
            r"expected.*before",
            r"missing.*before",
            r"promise.set_exception.*",
            r"use of deleted function",
            r"found .* in nested-name-specifier",
            r"has no member named",
            r"is not a member of",
            r"no type named.*in namespace",
            r"forming pointer",
            r"request for member",
            r"no longer supported",
            r"does not have any field",
            r"No such file or directory",
            r"is not a class, namespace, or enumeration",
            r"not in a namespace",
            r"is not a template",
            r"is not a class",
            r"not in namespace",
            r"not a namespace-name",
            r"not in class",
            r"return-statement with a value",
            r"must be a.*function",
            r"non-static data member",
            r"is not a.*member of",
            r"cannot be used as a function",
            r"assignment of.*location",
        ],
        "description": (
            "Malformed source or HPX/C++ misuse organization wise"
        ),
    },

    # Type errors, mostly conversions and scope 
    "Type_Error": {
        "patterns": [
            r"invalid initialization",
            r"use of .* before deduction of .*auto",
            r"deduced type .* is incomplete",
            r"cannot convert",
            r"could not convert",
            r"invalid template-id",
            r"invalid conversion",
            r"inconsistent types .* deduced",
            r"operands to .* have different types",
            r"return type .* is incomplete",
            r"assignment of member .* in read-only object",
            r"storage size of .* isn.*t known",
            r"operand type .* is incompatible with argument",
            r"is not an accessible base of",
            r"to refer to a type member of a template parameter.*use.*typename",
            r"static assertion failed:.*Requires at least forward iterator",
            r"static assertion failed:.*is_threads_executor",
            r"is not a constant expression",
            r"decrement of read-only variable",
            r"conversion from",
            r"base operand of .* is not a pointer",
            r"overloaded function with no contextual type information",
            r"static assertion failed:.*non-const references.*not supported",
            r"increment of read-only location",
            r"binding reference of type .* to .* discards qualifiers",
            r"invalid type argument of unary",
            r"operator.*must have either zero or one argument",
            r"void value not ignored as it ought to be",
            r"cannot resolve overloaded function .* based on conversion to type",
            r"assignment of read-only variable",
            r"converting function",
            r"is ambiguous",
            r"no match for",
            r"typedef declared",
            r"does not name a type",
            r"canont bind",
            r"no matching function",
            r"converting to",
            r"type/value mismatch",
            r"is not a type",
            r"cannot bind.*of type",
            r"template argument",
            r"invalid types.*for array subscript",
            r"was not declared in this scope",
            r"has not been declared",
            r"types may not be defined",
            r"may not appear in this context",
            r"incomplete type",
            r"not in type",
            r"no type named",
            r"unable to find.*operator",
            r"invalid operands of types",
            r"may not appear in a using-declaration",
            r"invalid.*from type",
        ],
        "description": "Correct names but wrong types or conversion errors",
    },

    # Incorrect use of C++ concepts in general
    "Declaration_Or_Function_Call_Error": {
        "patterns": [
            r"cannot have cv-qualifier",
            r"condition declares a function",
            r"statement cannot resolve address of overloaded function",
            r"must be a member function",
            r"invalid use of",
            r"cannot define friend function .* in a local class definition",
            r"must have either zero or one argument",
            r"declaration of .* shadows",
            r"cannot call member function",
            r"multiple types in one declaration",
            r"use of local variable",
            r"at non-class scope",
            r"static assertion failed:.*shall be Callable",
            r"has a different exception specifier",
            r"inline.*invalid in lambda",
            r"type-specifier invalid in lambda",
            r"is inaccessible within this context",
            r"declaration does not declare anything",
            r"parameter packs not expanded with",
            r"not expanded with",
            r"non-local lambda expression cannot have a capture-default",
            r"auto.*can only be specified for variables or function declarations",
            r"lambda parameter .* previously declared as a capture",
            r"cannot declare",
            r"forbids declaration",
            r"in declaration",
            r"function-definition is not allowed here",
            r"const.*can only be specified for objects and functions",
            r"does not name",
            r"qualified-id in declaration before",
            r"namespace.*definition is not allowed here",
            r"uninitialized",
            r"only constructors",
            r"conflicts with a previous declaration",
            r"conflicting declaration",
            r"multiple definition of",
            r"too many initializers",
            r"redefinition of",
            r"redeclaration",
            r"expression list treated as",
            r"redeclared",
            r"previous definition here",
            r"duplicate",
            r"argument given.*expected",
            r"wrong number of template arguments",
            r"forming reference to void",
            r"declared void",
            r"there are no arguments",
            r"passing.*argument",
            r"using.*after ‘class’",
            r"no declaration matches",
            r"invalid declarator",
            r"use of parameter from",
        ],
        "description": (
            "Valid syntax but violates C++ language rules on declaring "
            "and calling things"
        ),
    },

    # Usually tied to CMakeLists/Makefile/linking
    "Linker_Error": {
        "patterns": [
            r"undefined reference to",
            r"ld returned.*exit status",
            r"cannot find -l",
            r"unrecognized command-line option",
            r"command line processing: unrecognized option",
            r"hpx::exception_list::~exception_list\(\)",
            r"set_exception",
            r"exception_info.hpp",
            r"exception.hpp",
            r"exception_list",
            r"2.42-GCCcore-13.3.0/bin/ld",
            r"hpx::lcos::make_exceptional",
            r"detail::handle_local_exceptions",
            r"detail::static_partitioner",
        ],
        "description": "Linker errors",
    },

    # Runtime errors
    "Runtime_Error": {
        "patterns": [
            r"Segmentation fault",
            r"signal.*SIGSEGV",
            r"Aborted",
            r"out of memory",
            r"terminate called after throwing",
            r"srun:\s*error:.*Exited with exit code",
            r"srun:\s*error:.*task.*exited",
            r"slurmstepd:.*error:",
            # HPX runtime exception/error reporting
            r"hpx::detail::get_exception",
            r"hpx::detail::throw_exception",
            r"hpx::runtime_distributed::report_error",
            r"hpx::threads::.*report_error",
        ],
        "description": "Runtime failures",
    },

    # Catch-all
    "Other_Compilation": {
        "patterns": [],
        "description": "Other compilation errors not matched above",
    },
}


# ============================================================================
# ERROR EXTRACTION
# ============================================================================

def extract_error_lines(text: str, phase: str) -> List[str]:
    """
    Extract actual error lines.

    Build stderr:
        Trust compiler/linker error markers. Do not treat arbitrary uses of
        words such as "exception" as errors, since HPX headers and compiler
        context frequently contain them.

    Runtime stderr:
        Also recognize exception/crash diagnostics that do not use "error:".
    """
    if not text:
        return []

    errors = []

    for line in text.splitlines():
        # Skip compiler warnings/notes/info.
        if re.search(
            r":\s*(warning|note|info):",
            line,
            re.IGNORECASE,
        ):
            continue

        # --------------------------------------------------------------
        # BUILD + RUNTIME: explicit error diagnostics
        # --------------------------------------------------------------

        if re.search(r":\s*(fatal\s+)?error:", line, re.IGNORECASE):
            errors.append(line.strip())
            continue

        # Linker diagnostics.
        if re.search(r"undefined reference to", line, re.IGNORECASE):
            errors.append(line.strip())
            continue

        if re.search(r"ld returned.*exit status", line, re.IGNORECASE):
            errors.append(line.strip())
            continue

        if re.search(r"cannot find.*lib", line, re.IGNORECASE):
            errors.append(line.strip())
            continue

        # For compilation, stop here.
        #
        # This prevents lines such as:
        #
        #   In file included from .../exception_fwd.hpp
        #   hpx::exception
        #   void throw_exception(...)
        #
        # from being mistaken for compiler errors.
        if phase == "build":
            continue

        # --------------------------------------------------------------
        # RUNTIME ONLY
        # --------------------------------------------------------------

        if re.search(r"Segmentation fault", line, re.IGNORECASE):
            errors.append(line.strip())
            continue

        if re.search(r"signal.*SIGSEGV", line, re.IGNORECASE):
            errors.append(line.strip())
            continue

        if re.search(r"Aborted", line, re.IGNORECASE):
            errors.append(line.strip())
            continue

        if re.search(r"out of memory", line, re.IGNORECASE):
            errors.append(line.strip())
            continue

        if re.search(
            r"terminate called after throwing",
            line,
            re.IGNORECASE,
        ):
            errors.append(line.strip())
            continue

        # Broad exception matching is safe here because we already know
        # this is runtime stderr, not compiler include/template context.
        if re.search(r"exception", line, re.IGNORECASE):
            errors.append(line.strip())
            continue

        if re.search(r"runtime error", line, re.IGNORECASE):
            errors.append(line.strip())
            continue

        if re.search(r"assert.*failed", line, re.IGNORECASE):
            errors.append(line.strip())
            continue

    return errors


def categorize_error(error_line: str, phase: str) -> str:
    """Categorize a single error line based on configured patterns."""
    for category, config in ERROR_CATEGORIES.items():
        for pattern in config["patterns"]:
            if re.search(pattern, error_line, re.IGNORECASE):
                return category
    if phase == "runtime":
        return "Other_Runtime_Error" #record unexpected runtime to add tolist
    print(error_line)
    return "Other_Compilation"


# ============================================================================
# INPUT DISCOVERY
# ============================================================================

def discover_model_files(input_dir: str) -> Dict[str, str]:
    """
    Find supported <model>_combined.json files in the input directory.

    Example:
        glm_combined.json
            -> model_name = "glm"

        minimax_combined.json
            -> model_name = "minimax"

    Files for unsupported models are ignored.
    """
    model_files = {}

    suffix = "_combined.json"

    for filename in os.listdir(input_dir):
        if not filename.endswith(suffix):
            continue

        model_name = filename[:-len(suffix)]

        if model_name not in SUPPORTED_MODELS:
            continue

        filepath = os.path.join(input_dir, filename)

        if os.path.isfile(filepath):
            model_files[model_name] = filepath

    return model_files


def parse_results_file(filepath: str) -> List[Dict[str, Any]]:
    """Load one model's HPX validation results JSON file."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)

        if not isinstance(data, list):
            raise ValueError(
                "Expected the top-level JSON value to be a list."
            )

        return data

    except Exception as e:
        print(f"ERROR: Could not load {filepath}: {e}")
        return []
    


# ============================================================================
# RUNTIME STDERR SELECTION
# ============================================================================

def get_first_runtime_stderr(
    output: Dict[str, Any]
) -> Optional[Dict[str, Any]]:
    """
    Return information about the first run with nonempty stderr.

    Only ONE run contributes runtime stderr for each generated output.

    For example:

        thread 1  -> stderr empty
        thread 2  -> stderr empty
        thread 4  -> Segmentation fault
        thread 8  -> Segmentation fault
        thread 16 -> Segmentation fault

    Only the thread-4 stderr is analyzed.
    """
    runs = output.get("runs")

    if not runs or not isinstance(runs, list):
        return None

    for run_index, run in enumerate(runs):
        if not isinstance(run, dict):
            continue
        #ignore if it did_run
        if run.get("did_run"):
            continue
        stderr = run.get("stderr", "")
        
        if ignore_runtime_stderr(stderr): continue 

        if isinstance(stderr, str) and stderr.strip():
            return {
                "run_index": run_index,
                "num_threads": run.get("num_threads"),
                "stderr": stderr,
                "did_run": run.get("did_run"),
                "is_valid": run.get("is_valid"),
                "runtime": run.get("runtime"),
            }

    return None


# ============================================================================
# ANALYZE ONE GENERATED OUTPUT
# ============================================================================

def analyze_output(
    problem: Dict[str, Any],
    output: Dict[str, Any],
    output_number: int,
) -> Dict[str, Any]:
    """
    Analyze one generated output belonging to one HPX problem.

    The enclosing problem contains metadata such as:
        name
        problem_type
        language
        parallelism_model

    The output contains:
        generated_output
        did_build
        runs
        validation flags
        etc.
    """

    problem_name = problem.get("name", "unknown")
    problem_type = problem.get("problem_type", "unknown")
    language = problem.get("language", "unknown")
    parallelism_model = problem.get(
        "parallelism_model",
        "unknown",
    )

    build_error_counts = defaultdict(int)
    build_error_messages = defaultdict(list)
    build_error_rows = []

    runtime_error_counts = defaultdict(int)
    runtime_error_messages = defaultdict(list)
    runtime_error_rows = []

    # ------------------------------------------------------------------
    # BUILD STDERR
    # ------------------------------------------------------------------
    #
    # The example JSON does not show build_stderr, but support it in case
    # the full validation output contains it.
    #

    
    if output.get("did_build") is False:
        stderr_text = output.get("build_stderr", "")

        if isinstance(stderr_text, str) and stderr_text.strip():
            for error_line in extract_error_lines(stderr_text, phase="build"):
                category = categorize_error(
                    error_line,
                    phase="build",
                )

                build_error_counts[category] += 1

                if error_line not in build_error_messages[category]:
                    build_error_messages[category].append(error_line)

                build_error_rows.append({
                    "problem_name": problem_name,
                    "problem_type": problem_type,
                    "language": language,
                    "parallelism_model": parallelism_model,
                    "output_number": output_number,
                    "phase": "build",
                    "source": "build",
                    "num_threads": "",
                    "error_type": category,
                    "error_message": error_line,
                    "did_build": output.get("did_build"),
                    "is_source_valid": output.get("is_source_valid"),
                    "did_any_run": output.get("did_any_run"),
                    "did_all_run": output.get("did_all_run"),
                    "are_any_valid": output.get("are_any_valid"),
                    "are_all_valid": output.get("are_all_valid"),
                })

    # ------------------------------------------------------------------
    # RUNTIME STDERR
    # ------------------------------------------------------------------
    #
    # Only the first run containing stderr is analyzed.
    #

    first_runtime_error = get_first_runtime_stderr(
        output
    )

    if first_runtime_error is not None:
        stderr_text = first_runtime_error["stderr"]
        num_threads = first_runtime_error[
            "num_threads"
        ]
        run_index = first_runtime_error[
            "run_index"
        ]

        for error_line in extract_error_lines(stderr_text, phase="runtime"):
            category = categorize_error(
                    error_line, "runtime"
                )
        # #reomve validation fails (assertions usually)
        # if not is_validation_failure(stderr_text): 
        #     error_lines = extract_error_lines(
        #     stderr_text
        # )

            runtime_error_counts[category] += 1

            if error_line not in runtime_error_messages[category]:
                runtime_error_messages[category].append(error_line)

            runtime_error_rows.append({
                "problem_name": problem_name,
                "problem_type": problem_type,
                "language": language,
                "parallelism_model": parallelism_model,
                "output_number": output_number,
                "phase": "runtime",
                "source": f"run[{run_index}]",
                "num_threads": num_threads,
                "error_type": category, #always runtime anyway
                "error_message": error_line,
                "did_build": output.get("did_build"),
                "is_source_valid": output.get(
                    "is_source_valid"
                ),
                "did_any_run": output.get(
                    "did_any_run"
                ),
                "did_all_run": output.get(
                    "did_all_run"
                ),
                "are_any_valid": output.get(
                    "are_any_valid"
                ),
                "are_all_valid": output.get(
                    "are_all_valid"
                ),
            })

    total_build_errors = sum(
        build_error_counts.values()
    )

    total_runtime_errors = sum(
        runtime_error_counts.values()
    )

    return {
        "problem_name": problem_name,
        "problem_type": problem_type,
        "language": language,
        "parallelism_model": parallelism_model,
        "output_number": output_number,

        "did_build": output.get("did_build"),
        "is_source_valid": output.get(
            "is_source_valid"
        ),
        "did_any_run": output.get(
            "did_any_run"
        ),
        "did_all_run": output.get(
            "did_all_run"
        ),
        "are_any_valid": output.get(
            "are_any_valid"
        ),
        "are_all_valid": output.get(
            "are_all_valid"
        ),

        "build_error_counts": dict(
            build_error_counts
        ),
        "build_error_messages": dict(
            build_error_messages
        ),
        "build_error_rows": build_error_rows,

        "runtime_error_counts": dict(
            runtime_error_counts
        ),
        "runtime_error_messages": dict(
            runtime_error_messages
        ),
        "runtime_error_rows": runtime_error_rows,

        "first_runtime_error": first_runtime_error,

        "total_build_errors": total_build_errors,
        "total_runtime_errors": total_runtime_errors,
        "total_errors": (
            total_build_errors
            + total_runtime_errors
        ),
    }


# ============================================================================
# ANALYZE ALL PROBLEMS / OUTPUTS FOR ONE MODEL
# ============================================================================

def analyze_results(
    problems: List[Dict[str, Any]]
) -> List[Dict[str, Any]]:
    """
    Flatten:

        problem
            -> outputs[]
                -> generated output

    into one analysis record per generated output.
    """

    analyses = []

    for problem in problems:
        if not isinstance(problem, dict):
            continue

        outputs = problem.get(
            "outputs",
            [],
        )

        if not isinstance(outputs, list):
            print(
                "WARNING: Problem "
                f"{problem.get('name', 'unknown')} "
                "has an invalid outputs field."
            )
            continue

        # Zero-based numbering:
        #
        # outputs[0] -> output_number 0
        # outputs[1] -> output_number 1
        # ...
        #
        # Change to enumerate(outputs, start=1) if you
        # prefer human-oriented 1-based numbering.
        for output_number, output in enumerate(
            outputs
        ):
            if not isinstance(output, dict):
                continue

            analyses.append(
                analyze_output(
                    problem=problem,
                    output=output,
                    output_number=output_number,
                )
            )

    return analyses


# ============================================================================
# WRITE ONE MODEL'S ERROR CSV
# ============================================================================

def get_problem_types(
    problems: List[Dict[str, Any]]
) -> set:
    """Return all problem_type values present in a model's results."""
    return {
        problem.get("problem_type")
        for problem in problems
        if (
            isinstance(problem, dict)
            and problem.get("problem_type")
        )
    }
    
def write_error_csv(
    analyses: List[Dict[str, Any]],
    output_file: str,
    model_name: str,
    problem_type_filter: Optional[str] = None,
) -> int:
    """
    Write extracted errors for one model.

    If problem_type_filter is provided, only errors belonging to that
    problem type are written.
    """
    csv_rows = []

    for analysis in analyses:
        if (
            problem_type_filter is not None
            and analysis["problem_type"] != problem_type_filter
        ):
            continue

        for original_row in analysis["build_error_rows"]:
            row = dict(original_row)
            row["model"] = model_name
            csv_rows.append(row)

        for original_row in analysis["runtime_error_rows"]:
            row = dict(original_row)
            row["model"] = model_name
            csv_rows.append(row)

    fieldnames = [
        "model",
        "problem_name",
        "problem_type",
        "language",
        "parallelism_model",
        "output_number",
        "phase",
        "source",
        "num_threads",
        "error_type",
        "error_message",
        "did_build",
        "is_source_valid",
        "did_any_run",
        "did_all_run",
        "are_any_valid",
        "are_all_valid",
    ]

    with open(
        output_file,
        "w",
        newline="",
        encoding="utf-8",
    ) as f:
        writer = csv.DictWriter(
            f,
            fieldnames=fieldnames,
        )

        writer.writeheader()
        writer.writerows(csv_rows)

    return len(csv_rows)

# ============================================================================
# PRINT MODEL SUMMARY
# ============================================================================

def print_model_summary(
    model_name: str,
    analyses: List[Dict[str, Any]],
) -> None:
    """Print aggregate error statistics for one model."""

    total_outputs = len(analyses)

    outputs_with_errors = sum(
        1
        for analysis in analyses
        if analysis["total_errors"] > 0
    )

    total_build_errors = sum(
        analysis["total_build_errors"]
        for analysis in analyses
    )

    total_runtime_errors = sum(
        analysis["total_runtime_errors"]
        for analysis in analyses
    )

    build_counts = defaultdict(int)
    runtime_counts = defaultdict(int)

    for analysis in analyses:
        for category, count in analysis[
            "build_error_counts"
        ].items():
            build_counts[category] += count

        for category, count in analysis[
            "runtime_error_counts"
        ].items():
            runtime_counts[category] += count

    print()
    print(f"Summary for {model_name}:")
    print(
        f"  Generated outputs:    {total_outputs}"
    )
    print(
        f"  Outputs with errors:  {outputs_with_errors}"
    )
    print(
        f"  Build error rows:     {total_build_errors}"
    )
    print(
        f"  Runtime error rows:   {total_runtime_errors}"
    )

    if build_counts:
        print()
        print("  Build error categories:")

        for category in sorted(
            build_counts,
            key=lambda x: build_counts[x],
            reverse=True,
        ):
            print(
                f"    {category:38} "
                f"{build_counts[category]}"
            )

    if runtime_counts:
        print()
        print("  Runtime error categories:")

        for category in sorted(
            runtime_counts,
            key=lambda x: runtime_counts[x],
            reverse=True,
        ):
            print(
                f"    {category:38} "
                f"{runtime_counts[category]}"
            )


# ============================================================================
# MAIN
# ============================================================================

def main() -> None:
    if len(sys.argv) != 3:
        print(
            f"Usage: {sys.argv[0]} "
            "<input_directory> <output_directory>"
        )
        print()
        print("Example:")
        print(
            f"  python {sys.argv[0]} "
            "/work/pi_mrobson_smith_edu/scratch/"
            "generation_hpx/la/driver/tcmalloc "
            "./errors"
        )
        print()
        print(
            "The input directory should contain "
            "<model>_combined.json files."
        )
        print(
            "Currently analyzed models: "
            + ", ".join(
                sorted(SUPPORTED_MODELS)
            )
        )
        sys.exit(1)

    input_dir = sys.argv[1]
    output_dir = sys.argv[2]

    # ------------------------------------------------------------------
    # Validate input directory
    # ------------------------------------------------------------------

    if not os.path.isdir(input_dir):
        print(
            "ERROR: Input directory does not exist: "
            f"{input_dir}"
        )
        sys.exit(1)

    # ------------------------------------------------------------------
    # Create output directory
    # ------------------------------------------------------------------

    os.makedirs(
        output_dir,
        exist_ok=True,
    )

    # ------------------------------------------------------------------
    # Discover supported model JSON files
    # ------------------------------------------------------------------

    model_files = discover_model_files(
        input_dir
    )

    if not model_files:
        print(
            "ERROR: No supported *_combined.json "
            "files found."
        )
        print()
        print(
            "Currently supported models: "
            + ", ".join(
                sorted(SUPPORTED_MODELS)
            )
        )
        sys.exit(1)

    print("=" * 80)
    print("HPX ERROR EXTRACTION")
    print("=" * 80)
    print()
    print(
        f"Input directory:  {input_dir}"
    )
    print(
        f"Output directory: {output_dir}"
    )
    print()

    print("Relevant model JSON files found:")

    for model_name in sorted(model_files):
        print(
            f"  {model_name:10} -> "
            f"{os.path.basename(model_files[model_name])}"
        )

    # ------------------------------------------------------------------
    # Process each model independently
    # ------------------------------------------------------------------

    total_error_rows = 0
    total_outputs_processed = 0
    models_processed = 0

    for model_name in sorted(model_files):
        results_file = model_files[
            model_name
        ]

        print()
        print("=" * 80)
        print(
            f"PROCESSING MODEL: {model_name}"
        )
        print("=" * 80)
        print(
            f"Source JSON: {results_file}"
        )

        problems = parse_results_file(
            results_file
        )

        if not problems:
            print(
                "WARNING: No problem entries "
                f"found for {model_name}."
            )

            # Still create an empty CSV so that the
            # existence of the file indicates the model
            # was considered.
            output_csv = os.path.join(
                output_dir,
                f"{model_name}_errors.csv",
            )

            write_error_csv(
                analyses=[],
                output_file=output_csv,
                model_name=model_name,
            )

            print(
                f"Created empty CSV: {output_csv}"
            )
            continue

        total_outputs = sum(
            len(problem.get("outputs", []))
            for problem in problems
            if (
                isinstance(problem, dict)
                and isinstance(
                    problem.get("outputs", []),
                    list,
                )
            )
        )

        print(
            f"Problem entries:    {len(problems)}"
        )
        print(
            f"Generated outputs:  {total_outputs}"
        )

        analyses = analyze_results(
            problems
        )

        # --------------------------------------------------------------
        # Construct output filename from model name.
        #
        # glm_combined.json
        #       ->
        # glm_errors.csv
        # --------------------------------------------------------------

        problem_types = get_problem_types(problems)

        if "dense_la" in problem_types or "sparse_la" in problem_types:

            error_count = 0

            for la_type in ["dense_la", "sparse_la"]:

                if la_type not in problem_types:
                    continue

                la_output_dir = os.path.join(
                    output_dir,
                    la_type,
                )

                os.makedirs(
                    la_output_dir,
                    exist_ok=True,
                )

                output_csv = os.path.join(
                    la_output_dir,
                    f"{model_name}_errors.csv",
                )

                count = write_error_csv(
                    analyses=analyses,
                    output_file=output_csv,
                    model_name=model_name,
                    problem_type_filter=la_type,
                )

                error_count += count

                print(
                    f"Error CSV saved: {output_csv} "
                    f"({count} rows)"
                )

        else:

            output_csv = os.path.join(
                output_dir,
                f"{model_name}_errors.csv",
            )

            error_count = write_error_csv(
                analyses=analyses,
                output_file=output_csv,
                model_name=model_name,
            )

            print(
                f"Error CSV saved: {output_csv} "
                f"({error_count} rows)"
            )

            print_model_summary(
                model_name=model_name,
                analyses=analyses,
            )

            print()
            print(
                f"Error CSV saved: {output_csv}"
            )

            total_error_rows += error_count
            total_outputs_processed += len(
                analyses
            )
            models_processed += 1

    # ------------------------------------------------------------------
    # Final summary
    # ------------------------------------------------------------------

    print()
    print("=" * 80)
    print("DONE")
    print("=" * 80)

    print(
        f"Models processed:          {models_processed}"
    )
    print(
        f"Generated outputs scanned: {total_outputs_processed}"
    )
    print(
        f"Total error rows written:  {total_error_rows}"
    )
    print(
        f"Output directory:          {output_dir}"
    )

    print()
    print("Generated error CSVs:")

    for model_name in sorted(model_files):
        output_csv = os.path.join(
            output_dir,
            f"{model_name}_errors.csv",
        )

        print(
            f"  {output_csv}"
        )


if __name__ == "__main__":
    main()