import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""
NOTE: GENERATED BY SONNET LLM (SMITH GENAI)
"""
# --------------------------------------------------------------------------- #
# configuration                                                               #
# --------------------------------------------------------------------------- #
# Only generate graphs for these specific prompts
TARGET_PROMPTS = {
   #"40_sort_sort_an_array_of_complex_numbers_by_magnitude",
    #"46_sparse_la_spmm",
    
    # "39_search_xor_contains",
   # "64_locking_contention_lockingmat"
}
        
PROMPT_40_ANNOTATIONS = {
    "GPT5": 73,
    "Sonnet": 99,
    "HPC-Coder": 2,
    "Magicoder": 2,
}
ANNOTATION_OFFSETS_40 = {
    "GPT5": (10, 0),
    "Sonnet": (10, -15),
    "HPC-Coder": (10, 0),
    "Magicoder": (10, 15),  # Move down 15 points
}
PROMPT_46_ANNOTATIONS = {
    "GPT5": 89,
    "Sonnet": 6,
    "Magicoder": 13,
}

ANNOTATION_OFFSETS_46 = {
    "GPT5": (10, 0),
    "Sonnet": (10, 15),
    "Magicoder": (10, 0),  
}

PROMPT_64_ANNOTATIONS = {
    "GPT5": 41,
    "Sonnet": 80,
    "HPC-Coder": 16,
    "Starcoder": 49,
}
ANNOTATION_OFFSETS_64 = {
    "GPT5": (10, 15),
    "Sonnet": (10, -15),
    "HPC-Coder": (10, 0),
    "Magicoder": (10, 0),  # Move down 15 points
}


CSV_PATHS = [
    "/work/pi_mrobson_smith_edu/scratch/generation_hpx/fft/driver/tcmalloc/json_runtime_summary.csv",
    "/work/pi_mrobson_smith_edu/scratch/generation_hpx/graph/driver/tcmalloc/json_runtime_summary.csv",
    "/work/pi_mrobson_smith_edu/scratch/generation_hpx/transform/driver/tcmalloc/json_runtime_summary.csv",
    "/work/pi_mrobson_smith_edu/scratch/generation_hpx/scan/driver/tcmalloc/json_runtime_summary.csv",
    "/work/pi_mrobson_smith_edu/scratch/generation_hpx/search/driver/tcmalloc/json_runtime_summary.csv",
    "/work/pi_mrobson_smith_edu/scratch/generation_hpx/sort/driver/tcmalloc/json_runtime_summary.csv",
    "/work/pi_mrobson_smith_edu/scratch/generation_hpx/stencil/driver/tcmalloc/json_runtime_summary.csv",
    "/work/pi_mrobson_smith_edu/scratch/generation_hpx/locking_contention/driver/tcmalloc/json_runtime_summary.csv",
    "/work/pi_mrobson_smith_edu/scratch/generation_hpx/la/driver/tcmalloc/json_runtime_summary.csv",
    "/work/pi_mrobson_smith_edu/scratch/generation_hpx/reduce/driver/tcmalloc/json_runtime_summary.csv",
    "/work/pi_mrobson_smith_edu/scratch/generation_hpx/histogram/driver/tcmalloc/json_runtime_summary.csv",
    "/work/pi_mrobson_smith_edu/scratch/generation_hpx/geometry/driver/tcmalloc/json_runtime_summary.csv",
    "/work/pi_mrobson_smith_edu/scratch/generation_hpx/futures_promises/driver/tcmalloc/json_runtime_summary.csv"
]

THREADS = np.array([1, 2, 4, 8, 16, 32, 64], dtype=float)
RUNTIME_COLS = [f"runtime_{t}" for t in THREADS.astype(int)]
OUTPUT_ROOT = "/work/pi_mrobson_smith_edu/ParEval_amt/analysis/visuals_specific"

PASTEL_COLORS = [
    "#6BAED6",  # blue
    "#FD8D3C",  # orange
    "#74C476",  # green
    "#E377C2",  # pink
    "#9E9AC8",  # purple
    "#FFC658",  # yellow
    "#8DD3C7",  # teal
    "#BC80BD",  # lavender
]

MODEL_STYLES = {
    "gpt5_combined": {"label": "GPT5", "color": PASTEL_COLORS[0]},
    "hpc-coder_combined": {"label": "HPC-Coder", "color": PASTEL_COLORS[1]},
    "starcoder_combined": {"label": "Starcoder", "color": PASTEL_COLORS[4]},
    "magicoder_combined": {"label": "Magicoder", "color": PASTEL_COLORS[2]},
    "sonnet_combined": {"label": "Sonnet", "color": PASTEL_COLORS[3]},
    "glm_combined": {"label": "GLM", "color": PASTEL_COLORS[5]},
    "oss_combined": {"label": "OSS", "color": PASTEL_COLORS[6]},
    "minimax_combined": {"label": "MiniMax", "color": PASTEL_COLORS[7]},
    
}
MODEL_ORDER = ["GPT5", "HPC-Coder", "Starcoder", "Magicoder", "Sonnet", "GLM", "OSS", "MiniMax"]

plt.rcParams.update(
    {
        "font.size": 11,
        "axes.grid": True,
        "grid.alpha": 0.3,
        "grid.linestyle": "--",
        "axes.spines.top": False,
        "axes.spines.right": False,
    }
)


# --------------------------------------------------------------------------- #
# helpers                                                                     #
# --------------------------------------------------------------------------- #
def safe_filename(name: str) -> str:
    """Turn an arbitrary string into something safe for filenames."""
    name = name.strip()
    name = re.sub(r"[^\w\-\. ]+", "_", name)
    return name.replace(" ", "_")


def get_prompt_category(csv_path: str) -> str:
    parts = csv_path.split(os.sep)
    try:
        idx = parts.index("generation_hpx")
        return parts[idx + 1]
    except (ValueError, IndexError):
        return "unknown"


# --------------------------------------------------------------------------- #
# main plotting                                                               #
# --------------------------------------------------------------------------- #
print(f"Filtering for {len(TARGET_PROMPTS)} specific prompt(s): {', '.join(sorted(TARGET_PROMPTS))}\n")

generated_count = 0

for csv_path in CSV_PATHS:
    if not os.path.isfile(csv_path):
        print(f"[skip] Missing CSV: {csv_path}")
        continue

    df = pd.read_csv(csv_path)

    if "name" not in df.columns:
        print(f"[warn] 'name' column missing in {csv_path}; skipping.")
        continue

    # Filter dataframe to only include target prompts
    df = df[df["name"].isin(TARGET_PROMPTS)]
    
    if df.empty:
        continue  # No target prompts in this CSV, skip silently

    available_cols = [col for col in RUNTIME_COLS if col in df.columns]
    available_threads = THREADS[[RUNTIME_COLS.index(col) for col in available_cols]]

    if not available_cols:
        print(f"[warn] No runtime_* columns found in {csv_path}; skipping.")
        continue

    prompt_category = get_prompt_category(csv_path)
    category_dir = os.path.join(OUTPUT_ROOT, prompt_category)
    os.makedirs(category_dir, exist_ok=True)

    for prompt_name, group in df.groupby("name", sort=False):
        # Double-check the prompt name is in our target list
        if prompt_name not in TARGET_PROMPTS:
            continue

        fig, ax = plt.subplots(figsize=(7.5, 4.75))

        plotted_any = False
        max_runtime = 0.0  # Track the maximum runtime value
        line_endpoints = {}
        for _, row in group.iterrows():
            model_key = row.get("model", "(unknown model)")
            style = MODEL_STYLES.get(model_key, None)

            if style is None:
                display_label = model_key
                color = "#333333"
            else:
                display_label = style["label"]
                color = style["color"]

            runtimes = row[available_cols].to_numpy(dtype=float, copy=True)
            mask = np.isfinite(runtimes)
            if mask.sum() == 0:
                continue

            # Update maximum runtime
            max_runtime = max(max_runtime, np.max(runtimes[mask]))

            ax.plot(
                available_threads[mask],
                runtimes[mask],
                marker="o",
                linewidth=2,
                markersize=6,
                color=color,
                label=display_label,
            )
            plotted_any = True
            
             # Store the rightmost point for annotation
            rightmost_thread = available_threads[mask][-1]
            rightmost_runtime = runtimes[mask][-1]
            line_endpoints[display_label] = {
                "x": rightmost_thread,
                "y": rightmost_runtime,
                "color": color
            }

        if not plotted_any:
            plt.close(fig)
            continue

        # Set y-axis limits: 0 to 1.2 times the maximum runtime
        if max_runtime > 0:
            ax.set_ylim(0, max_runtime * 1.2)

        ax.set_xscale("log", base=2)
        ax.set_xticks(THREADS)
        ax.get_xaxis().set_major_formatter(plt.ScalarFormatter())
        ax.set_xlabel("Number of Threads")
        ax.set_ylabel("Runtime (s)")

        prompt_category_title = prompt_category.replace("_", " ").title()
        if prompt_category and prompt_category.lower() in prompt_name.lower():
            pattern = re.compile(re.escape(prompt_category), flags=re.IGNORECASE)
            prompt_title = pattern.sub(prompt_category_title, prompt_name)
        else:
            prompt_title = prompt_name
        ax.set_title(prompt_title)

        handles, labels = ax.get_legend_handles_labels()
        label_to_handle = {}
        for handle, label in zip(handles, labels):
            label_to_handle[label] = handle
        ordered_labels = [label for label in MODEL_ORDER if label in label_to_handle]
        ordered_handles = [label_to_handle[label] for label in ordered_labels]
        if ordered_handles:
            ax.legend(ordered_handles, ordered_labels, frameon=False)
        else:
            ax.legend(frameon=False)
            
        if prompt_name == "40_sort_sort_an_array_of_complex_numbers_by_magnitude":
            if ordered_handles:
                ax.legend(ordered_handles, ordered_labels, frameon=False, 
                loc='upper right', bbox_to_anchor=(1.0, 0.8))
            
            for model_label, annotation_value in PROMPT_40_ANNOTATIONS.items():
                if model_label in line_endpoints:
                    endpoint = line_endpoints[model_label]
                    offset = ANNOTATION_OFFSETS_40.get(model_label, (10,0)) 
                    
                    
                    # Position annotation slightly to the right of the last point
                    ax.annotate(
                        str(annotation_value),
                        xy=(endpoint["x"], endpoint["y"]),
                        xytext=offset,  # 10 points to the right
                        textcoords="offset points",
                        fontsize=10,
                        fontweight='bold',
                        color=endpoint["color"],
                        bbox=dict(
                            boxstyle="round,pad=0.4",
                            facecolor='white',
                            edgecolor=endpoint["color"],
                            linewidth=2,
                            alpha=0.9
                        ),
                        ha='left',
                        va='center'
                    )
                    
        elif prompt_name == "46_sparse_la_spmm":
            if ordered_handles:
                ax.legend(ordered_handles, ordered_labels, frameon=False, 
                loc='upper right', bbox_to_anchor=(1.0, 0.8))
            
            for model_label, annotation_value in PROMPT_46_ANNOTATIONS.items():
                if model_label in line_endpoints:
                    endpoint = line_endpoints[model_label]
                    offset = ANNOTATION_OFFSETS_46.get(model_label, (10,0)) 
                    
                    
                    # Position annotation slightly to the right of the last point
                    ax.annotate(
                        str(annotation_value),
                        xy=(endpoint["x"], endpoint["y"]),
                        xytext=offset,  # 10 points to the right
                        textcoords="offset points",
                        fontsize=10,
                        fontweight='bold',
                        color=endpoint["color"],
                        bbox=dict(
                            boxstyle="round,pad=0.4",
                            facecolor='white',
                            edgecolor=endpoint["color"],
                            linewidth=2,
                            alpha=0.9
                        ),
                        ha='left',
                        va='center'
                    )
                    
        elif prompt_name == "64_locking_contention_lockingmat":
            if ordered_handles:
                ax.legend(ordered_handles, ordered_labels, frameon=False, 
                loc='upper left', bbox_to_anchor=(0.1, 0.95))
            
            for model_label, annotation_value in PROMPT_64_ANNOTATIONS.items():
                if model_label in line_endpoints:
                    endpoint = line_endpoints[model_label]
                    offset = ANNOTATION_OFFSETS_64.get(model_label, (10,0)) 
                    
                    
                    # Position annotation slightly to the right of the last point
                    ax.annotate(
                        str(annotation_value),
                        xy=(endpoint["x"], endpoint["y"]),
                        xytext=offset,  # 10 points to the right
                        textcoords="offset points",
                        fontsize=10,
                        fontweight='bold',
                        color=endpoint["color"],
                        bbox=dict(
                            boxstyle="round,pad=0.4",
                            facecolor='white',
                            edgecolor=endpoint["color"],
                            linewidth=2,
                            alpha=0.9
                        ),
                        ha='left',
                        va='center'
                    )

        fig.tight_layout()

        file_safe_prompt = safe_filename(prompt_name)
        output_path = os.path.join(category_dir, f"{file_safe_prompt}_runtime_vs_threads.png")
        fig.savefig(output_path, dpi=300)
        plt.close(fig)

        generated_count += 1
        print(f"[ok] Saved {prompt_category} → {prompt_name}: {output_path}")

print(f"\n{'='*60}")
print(f"Generated {generated_count} graph(s) for target prompts.")
print(f"{'='*60}")